name: Release to NPM

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Replace version placeholder
        run: |
          cd dist/signals-http-tracking
          # Replace placeholder with actual version from git tag
          sed -i 's/"version": "#{GITHUB_TAG_VERSION}#"/"version": "${{ steps.version.outputs.VERSION }}"/g' package.json
          echo "Version placeholder replaced with: ${{ steps.version.outputs.VERSION }}"
          # Verify the change
          grep '"version":' package.json

      - name: Publish to NPM
        run: |
          cd dist/signals-http-tracking
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ steps.version.outputs.VERSION }}" \
            --notes "## Release ${{ steps.version.outputs.VERSION }}
          
          **Installation:**
          \`\`\`bash
          npm install signals-http-tracking@${{ steps.version.outputs.VERSION }}
          \`\`\`
          
          Published to npm: https://www.npmjs.com/package/signals-http-tracking/v/${{ steps.version.outputs.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}